name: mongoCI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  mongo:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Deps
        run: npm install
      - name: Run tests on MONGO
        run: npm test 
        env:
          DB: mongo