name: mongoCI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  mongo:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.x, 12.x, 14.x]
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    name: Node ${{ matrix.node-version }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: npm install
      - name: Run tests on MONGO
        timeout-minutes: 3
        run: npm test 
        env:
          DB: mongo